### PR TITLE
Save credentials to local configuration file

### PR DESCRIPTION
**Pull request by rost314**
Avoid entering login and password every time by saving it to a local configuration file.

### CODE REVIEW

**Comment by chrisz** [comment]
Thanks for the patch :-)

**Comment by rost314** [comment]
cool :-)

**Comment by chrisz** [comment]
Hi,

I had a contributors section in the README. If you want, I can add your name or pseudo in front of your github id.

I made some modification about your patch. Now, we need to add the option --save to save information in automower.cfg (the password is in plain text so I prefer avoiding to save it implicitly).

Chris

**Comment by rost314** [comment]
Hi Chris,

thanks for adding me to the contributor list. I'm fine with it. 
I understand your concerns about the password and the --save option is a good solution. What do you think about some rudimentary obfuscation for the stored password like base64 encoding so that at least no one can read the password just by accident?

Robert

**Comment by chrisz** [comment]
Hi Robert,

I prefer to keep password in plain text. If we try to obfuscate the password, users could think the configuration file is secured and store it in "public place". If users don't use the same password for other services, it's not really a problem...

Chris

**Pull request merged**
