### PR TITLE
Better token support and status logger

### PR DESCRIPTION
**Pull request by CaselIT**
Hi @chrisz 
First of all thanks for writing this library!

I've added some changes for my own personal use, but I think some of them could be useful to others

The main changes are:
- Better token support: once the server grant us a token we reuse it until it expires. This avoids the login and logout steps that were previously done for every request.
- Added support for more than one mower
- Added a logger to periodically log the status of the mower for a set number of days

Let my know if you have some suggestion

### CODE REVIEW

**Comment by CaselIT** [comment]
Hi @chrisz, when you have time, can you give me a feedback?
Thanks

**Comment by chrisz** [comment]
Hi @CaselIT 

Sorry for the delay, I'm a little bit busy these days.

I just checkout your branch. Review is ok and tests ok too :-).

Thank you for these improvements :-)

Chris

**Comment by CaselIT** [comment]
Thanks @chrisz 
Out of curiosity did you find a reference document for the husqvarna api, or did you just tried until it worked?

**Comment by chrisz** [comment]
No reference document but the apk "Automower Connect" contains a js file with the code of the application... so I just extract commands to write this script.

**Comment by richardpub4136** [comment]
Do you know these elements from Husqvarna ??
https://github.com/husqvarnagroup/hcp

Personally I do not have enough skills but it seems to me that it describes quite precisely the operation of the application husqvarna

**Comment by CaselIT** [comment]
@richardpub4136 I've had a quick look at that repo, but I don't think its related to the rest api protocol.
When I've time I'll take a closer look.
Thanks for the heads up

**Comment by chrisz** [comment]
@richardpub4136 I agree with @CaselIT , I don't think we can use hcp to control automower using rest api. hcp seems to be a framework to control mowers at low level, maybe via the usb wire.
And I have the impression that codecs are missing and without codec (specifications of commands), hcp is useless.
But maybe I didn't understand this project.

**Pull request merged**
